import type { CSSProperties } from "react";

export const users = [
  {
    role: "Architect",
    name: "Maria Bailo Newton",
    username: "mbailo",
    email: "maria.bailo@baigunrealty.com",
    avatarUrl: "https://placehold.co/100x100.png",
    aiHint: "woman professional",
    initials: "MN",
    lots: {
      tomarAccion: 5,
      tasacion: 2,
      evolucionando: 8,
      disponible: 10,
      descartado: 1,
      noVende: 3,
      reservado: 0,
      vendido: 4,
    },
  },
  {
    role: "Asesor",
    name: "Roxana Rajich",
    username: "rrajich",
    email: "roxana.rajich@baigunrealty.com",
    avatarUrl: "https://placehold.co/100x100.png",
    aiHint: "woman smiling",
    initials: "RR",
    lots: {
      tomarAccion: 12,
      tasacion: 8,
      evolucionando: 15,
      disponible: 5,
      descartado: 2,
      noVende: 1,
      reservado: 3,
      vendido: 7,
    },
  },
  {
    role: "Asesor",
    name: "Santiago Liscovsky",
    username: "sliscovsky",
    email: "santiago.liscovsky@baigunrealty.com",
    avatarUrl: "https://placehold.co/100x100.png",
    aiHint: "man professional",
    initials: "SL",
    lots: {
      tomarAccion: 3,
      tasacion: 5,
      evolucionando: 7,
      disponible: 12,
      descartado: 0,
      noVende: 4,
      reservado: 2,
      vendido: 9,
    },
  },
  {
    role: "Asesor",
    name: "Martín Beorlegui",
    username: "mbeorlegui",
    email: "martin.beorlegui@baigunrealty.com",
    avatarUrl: "https://placehold.co/100x100.png",
    aiHint: "man portrait",
    initials: "MB",
    lots: {
      tomarAccion: 8,
      tasacion: 4,
      evolucionando: 10,
      disponible: 8,
      descartado: 3,
      noVende: 2,
      reservado: 1,
      vendido: 6,
    },
  },
  {
    role: "Asesor",
    name: "Iair Baredes",
    username: "ibaredes",
    email: "iair.baredes@baigunrealty.com",
    avatarUrl: "https://placehold.co/100x100.png",
    aiHint: "man happy",
    initials: "IB",
    lots: {
      tomarAccion: 7,
      tasacion: 6,
      evolucionando: 9,
      disponible: 11,
      descartado: 1,
      noVende: 1,
      reservado: 4,
      vendido: 5,
    },
  },
  {
    role: "Asesor",
    name: "Ariel Naem",
    username: "anaem",
    email: "ariel.naem@baigunrealty.com",
    avatarUrl: "https://placehold.co/100x100.png",
    aiHint: "man with glasses",
    initials: "AN",
    lots: {
      tomarAccion: 9,
      tasacion: 3,
      evolucionando: 12,
      disponible: 7,
      descartado: 4,
      noVende: 0,
      reservado: 2,
      vendido: 8,
    },
  },
  {
    role: "Administrador",
    name: "Matías Poczter",
    username: "mpoczter",
    email: "matias.poczter@baigunrealty.com",
    avatarUrl: "https://placehold.co/100x100.png",
    aiHint: "person smiling",
    initials: "MP",
    lots: {
      tomarAccion: 2,
      tasacion: 1,
      evolucionando: 5,
      disponible: 15,
      descartado: 0,
      noVende: 0,
      reservado: 5,
      vendido: 20,
    },
  },
  {
    role: "Administrador",
    name: "Matias Chirom",
    username: "mchirom",
    email: "matias.chirom@baigunrealty.com",
    avatarUrl: "https://placehold.co/100x100.png",
    aiHint: "man office",
    initials: "MC",
    lots: {
      tomarAccion: 4,
      tasacion: 3,
      evolucionando: 6,
      disponible: 18,
      descartado: 1,
      noVende: 2,
      reservado: 3,
      vendido: 15,
    },
  },
];

export const listings = [
  {
    address: "Av. Santa Fe 1060",
    neighborhood: "Palermo",
    smp: "017-027-020A",
    area: 110,
    status: "Tomar Acción",
    agent: { name: "Ariel Naem", initials: "AN" },
    imageUrl: null,
    origen: "Tor",
    codigoUrbanistico: "U.S.A.M.",
    cpu: "R2b1",
    partida: "123456-7",
    valorVentaUSD: 1300000,
    listingDate: new Date('2024-07-15'),
    saleDate: null,
  },
  {
    address: "Juramento 1196",
    neighborhood: "Belgrano",
    smp: "017-059-048D",
    area: 162,
    status: "Disponible",
    agent: { name: "Santiago Liscovsky", initials: "SL" },
    imageUrl: "https://placehold.co/600x400.png",
    aiHint: "modern apartment building",
    origen: "Baigun Realty",
    codigoUrbanistico: "C.M.",
    cpu: "R1a",
    partida: "234567-8",
    valorVentaUSD: 2500000,
    listingDate: new Date('2024-07-01'),
    saleDate: null,
  },
  {
    address: "Rivadavia 1298",
    neighborhood: "Caballito",
    smp: "017-027-006",
    area: 185,
    status: "Evolucionando",
    agent: { name: "Iair Baredes", initials: "IB" },
    imageUrl: "https://placehold.co/600x400.png",
    aiHint: "storefront supermarket",
    origen: "Producción",
    codigoUrbanistico: "U.S.A.A.",
    cpu: "C3II",
    partida: "345678-9",
    valorVentaUSD: 1800000,
    listingDate: new Date('2024-06-20'),
    saleDate: null,
  },
  {
    address: "Corrientes 1341",
    neighborhood: "Almagro",
    smp: "031-036-034",
    area: 174,
    status: "Disponible",
    agent: { name: "Martín Beorlegui", initials: "MB" },
    imageUrl: "https://placehold.co/600x400.png",
    aiHint: "industrial warehouse",
    origen: "Tor",
    codigoUrbanistico: "C.M.",
    cpu: "C1",
    partida: "456789-0",
    valorVentaUSD: 1750000,
    listingDate: new Date('2024-07-05'),
    saleDate: null,
  },
  {
    address: "Scalabrini Ortiz 1494",
    neighborhood: "Recoleta",
    smp: "017-026-022",
    area: 210,
    status: "Descartado",
    agent: { name: "Ariel Naem", initials: "AN" },
    imageUrl: "https://placehold.co/600x400.png",
    aiHint: "old city building",
    origen: "Baigun Realty",
    codigoUrbanistico: "A.E.",
    cpu: "R1b",
    partida: "567890-1",
    valorVentaUSD: 3200000,
    listingDate: new Date('2024-04-10'),
    saleDate: null,
  },
  {
    address: "Quintana 1577",
    neighborhood: "San Telmo",
    smp: "031-053-037",
    area: 150,
    status: "No vende",
    agent: { name: "Matías Poczter", initials: "MP" },
    imageUrl: "https://placehold.co/600x400.png",
    aiHint: "yellow historic house",
    origen: "Producción",
    codigoUrbanistico: "A.P.H.",
    cpu: "APH1",
    partida: "678901-2",
    valorVentaUSD: 1500000,
    listingDate: new Date('2024-03-22'),
    saleDate: null,
  },
  {
    address: "Defensa 1684",
    neighborhood: "Villa Crespo",
    smp: "031-055-029",
    area: 195,
    status: "Reservado",
    agent: { name: "Matias Chirom", initials: "MC" },
    imageUrl: "https://placehold.co/600x400.png",
    aiHint: "suburban brick house",
    origen: "Tor",
    codigoUrbanistico: "U.S.A.B.2",
    cpu: "R2bII",
    partida: "789012-3",
    valorVentaUSD: 2100000,
    listingDate: new Date('2024-06-28'),
    saleDate: null,
  },
  {
    address: "Av. Cordoba 1800",
    neighborhood: "Recoleta",
    smp: "031-114-032",
    area: 95,
    status: "Vendido",
    agent: { name: "Maria Bailo Newton", initials: "MN" },
    imageUrl: "https://placehold.co/600x400.png",
    aiHint: "red modern house",
    origen: "Baigun Realty",
    codigoUrbanistico: "C.M.",
    cpu: "C3I",
    partida: "890123-4",
    valorVentaUSD: 950000,
    listingDate: new Date('2024-05-10'),
    saleDate: new Date('2024-07-25'),
  },
  {
    address: "Honduras 4880",
    neighborhood: "Palermo",
    smp: "017-027-021A",
    area: 120,
    status: "Vendido",
    agent: { name: "Roxana Rajich", initials: "RR" },
    imageUrl: "https://placehold.co/600x400.png",
    aiHint: "modern house",
    origen: "Producción",
    codigoUrbanistico: "U.S.A.M.",
    cpu: "R2b1",
    partida: "901234-5",
    valorVentaUSD: 1150000,
    listingDate: new Date('2024-02-05'),
    saleDate: new Date('2024-06-15'),
  },
  {
    address: "Av. Cabildo 2040",
    neighborhood: "Belgrano",
    smp: "017-059-049D",
    area: 170,
    status: "Tasación",
    agent: { name: "Santiago Liscovsky", initials: "SL" },
    imageUrl: "https://placehold.co/600x400.png",
    aiHint: "luxury apartment",
    origen: "Tor",
    codigoUrbanistico: "C.M.",
    cpu: "R1a",
    partida: "012345-6",
    valorVentaUSD: 2800000,
    listingDate: new Date('2024-07-18'),
    saleDate: null,
  },
];

export const getStatusStyles = (status: string): CSSProperties => {
  const styles: { [key: string]: { backgroundColor: string; color: string } } = {
    "Tomar Acción": { backgroundColor: "#669bbc", color: "#ffffff" },
    "Tasación": { backgroundColor: "#dda15e", color: "#ffffff" },
    "Evolucionando": { backgroundColor: "#219ebc", color: "#ffffff" },
    "Disponible": { backgroundColor: "#ffb703", color: "#000000" },
    "Descartado": { backgroundColor: "#0d1b2a", color: "#ffffff" },
    "No vende": { backgroundColor: "#c1121f", color: "#ffffff" },
    "Reservado": { backgroundColor: "#fb8500", color: "#ffffff" },
    "Vendido": { backgroundColor: "#4f772d", color: "#ffffff" },
  };

  return styles[status] || {};
};
